server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript application/octet-stream;
    gzip_min_length 256;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(data|wasm|js)$ {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=31536000";
    }

    location ~* \.br$ {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=31536000";
        add_header Content-Encoding br;
        types { application/octet-stream br; }
        default_type application/octet-stream;
        try_files $uri =404;
    }

    location ~* \.gz$ {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=31536000";
        add_header Content-Encoding gzip;
        try_files $uri =404;
    }

    location /Build/ {
        add_header Access-Control-Allow-Origin *;
        try_files $uri =404;
    }
}
